default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:1054208384677:android:a6d41d143948d4bc83f74c",
        firebase_cli_token: "1//03zu-8WgroJ_yCgYIARAAGAMSNwF-L9Ir41LyzDJVA5FQP8AqgNOX_HHqc57I32OBqQRmdPCJ6KzF0dD7gG-v-d-FHz4YU4lUq_A",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "youseftareq182002@gmail.com",
        release_notes: "First Fastlane Firebase Distribution"
  )
  end
end
